#!/bin/bash
#SBATCH --job-name=HMWK06
#SBATCH --partition=batch
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=20gb
#SBATCH --time=24:00:00
#SBATCH --output=log.%j
#SBATCH --mail-user=lo50936@uga.edu
#SBATCH --mail-type=END,FAIL
#SBATCH --output=/work/gene8940/lo50936/log.%j

#Working directory
mkdir "/work/gene8940/lo50936/HMW05"
BASEDIR="/work/gene8940/lo50936/HMW05"
cd /work/gene8940/lo50936/HMW05
