#!/bin/bash
#SBATCH --job-name=testBEDTOOL
#SBATCH --partition=batch
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=20gb
#SBATCH --time=2:00:00
#SBATCH --output=log.%j
#SBATCH --mail-user=jm45001@uga.edu
#SBATCH --mail-type=END,FAIL
#SBATCH --output=/work/gene8940/jm45001/log.%j

mkdir /work/gene8940/lo50936/Homework3
BASEDIR="/work/gene894/lo50936/Homework3"
curl -s ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/005/845/GCF_000005845.2_ASM584v2/GCF_000005845.2_ASM584v2_genomic.fna.gz | gunzip -c > $BASEDIR/ecoli_MG1655_ncbi_refseq.fna
curl -s ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/005/845/GCF_000005845.2_ASM584v2/GCF_000005845.2_ASM584v2_genomic.gff.gz | gunzip -c > $BASEDIR/ecoli_MG1655_ncbi_refseq.gff

module load BEDOPS/2.4.30
module load BEDTools/2.26.0-foss-2016b

cd /work/gene8940/lo50936/Homework3

convert2bed --input=gff [output=bed] <ecoli_MG1655_ncbi_refseq.gff> ecoli_MG1655_ncbi_refseq.bed

grep "CDS" ecoli_MG1655_ncbi_refseq.bed > CDS.bed

module load SAMtools/1.6-foss-2016b
samtools faidx ecoli_MG1655_ncbi_refseq.fna

cut -f1-2 ecoli_MG1655_ncbi_refseq.fna.fai > genome.txt

bedtools complement -i CDS.bed -g genome.txt> Non_CDS.bed
bedtools getfasta -fi ecoli_MG1655_ncbi_refseq.fna -bed CDS.bed >CDS.fa
bedtools getfasta -fi ecoli_MG1655_ncbi_refseq.fna -bed Non_CDS.bed >Non_CDS.fa

module load ucsc/359

faCount -summary CDS.fa
faCount -summary Non_CDS.fa
