#!/bin/bash
#SBATCH --job-name=HMWK06
#SBATCH --partition=batch
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=20gb
#SBATCH --time=24:00:00
#SBATCH --output=log.%j
#SBATCH --mail-user=lo50936@uga.edu
#SBATCH --mail-type=END,FAIL
#SBATCH --output=/work/gene8940/lo50936/log.%j

#Working directory
mkdir "/work/gene8940/lo50936/HMW06"
BASEDIR="/work/gene8940/lo50936/HMW06"
cd /work/gene8940/lo50936/HMW06


#Downloads reads and refrence sequence
module load SRA-Toolkit/2.9.1-centos_linux64

#Ecoli_wild-type_rep1_anaerobic RNA-seq (Ecoli_wt1)
fastq-dump --split-files --gzip SRR5344681
#Ecoli_wild-type_rep2_anaerobic RNA-seq (Ecoli_wt2)
fastq-dump --split-files --gzip SRR5344682
#Ecoli_dFNR_rep1_anaerobic RNA-seq (Ecoli_dFNR1)
fastq-dump --split-files --gzip SRR5344683
#Ecoli_dFNR_rep2_anaerobic RNA-seq (Ecoli_dFNR2)
fastq-dump --split-files --gzip SRR5344684

#Reference strain
curl -s ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/005/845/GCF_000005845.2_ASM584v2/GCF_000005845.2_ASM584v2_genomic.fna.gz | gunzip -c > $BASEDIR/ecoli_MG1655_ncbi_refseq.fna

#Kallisto index and quant
module load kallisto/0.43.1-foss-2016b
kallisto index -i transcripts.idx ecoli_MG1655_ncbi_refseq.fna
kallisto quant -i transcripts.idx -o Ecoli_wt1 -b 100 -t 1 SRR5344681_1.fastq.gz SRR5344681_2.fastq.gz
kallisto quant -i transcripts.idx -o Ecoli_wt2 -b 100 -t 1 SRR5344682_1.fastq.gz SRR5344682_2.fastq.gz
kallisto quant -i transcripts.idx -o Ecoli_dFNR1 -b 100 -t 1 SRR5344683_1.fastq.gz SRR5344683_2.fastq.gz
kallisto quant -i transcripts.idx -o Ecoli_dFNR2 -b 100 -t 1 SRR5344684_1.fastq.gz SRR5344684_2.fastq.gz

mkdir $BASEDIR/kallisto_results
mv Ecoli*/ $BASEDIR/kallisto_results

#R
#module load R/3.4.4-foss-2016b-X11-20160819-GACRC
#R --no-save < /home/lo50936/GENE8940/HMW06/ecoli-rnaseq-sleuth_HMW06.sh
